# Generated by Django 5.1.6 on 2025-02-22 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0003_category_challenge_test_cases_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='test_cases',
            field=models.JSONField(default=list),
        ),
    ]
